yellow-jacket-coverage:
  image: node:24

  stage: test

  script:
    - npm ci
    - npx yellow-jacket coverage --gitlab --output yellow-jacket-junit.xml

  artifacts:
    when: always

    reports:
      junit:
        - yellow-jacket-junit.xml

    paths:
      - yellow-jacket-junit.xml

    expire_in: 1 week
